export const COLORS= {
    blue : '#c9d3ff',
    blueActive : '#ffedc1',
    blueFont : '#eceefb',
    blueFontActive : '#c9d3ff',
    blueFontButton: '#eceefb',
    blueNavBackground:'#ffedc1',
    blueNavLine:'#c9d3ff',
    blueNavFont:'#101012',
    yellow : '#f2ce69',
    yellowActive : '#4d4d4d',
    yellowFont : '#ffffff',
    yellowFontActive : '#f2ce69',
    yellowFontButton: '#4d4d4d',
    yellowNavBackground:'#4d4d4d',
    yellowNavLine:'#ffffff',
    yellowNavFont:'#f2ce69',
    orange : '#dfb589',
    orangeActive : '#cc6700',
    orangeFont : '#ffffff',
    orangeFontActive : '#dfb589',
    orangeFontButton: '#cc6700',
    orangeNavBackground:'#cc6700',
    orangeNavLine:'#ffffff',
    orangeNavFont:'#dfb589',
    red : '#e14949',
    redActive : '#302e2e',
    redFont : '#ffffff',
    redFontActive : '#e14949',
    redFontButton: '#302e2e',
    redNavBackground:'#302e2e',
    redNavLine:'#e14949',
    redNavFont:'#ffffff',
    green : '#58946e',
    greenActive : '#f2d3b2',
    greenFont : '#ffffff',
    greenFontActive : '#58946e',
    greenFontButton: '#f2d3b2',
    greenNavBackground:'#f2d3b2',
    greenNavLine:'#ffffff',
    greenNavFont:'#58946e',
    white : '#fcfcfc',
    whiteActive : '#0f4c82',
    whiteFont : '#b7b7b7',
    whiteFontActive : '#fcfcfc',
    whiteFontButton: '#0f4c82',
    whiteNavBackground:'#0f4c82',
    whiteNavLine:'#b7b7b7',
    whiteNavFont:'#ffffff'
};
